export const VendorElectABI = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "RatingCompleted",
    type: "event",
  },
  {
    inputs: [],
    name: "getItemGrades",
    outputs: [
      { internalType: "euint8", name: "capital", type: "uint256" },
      { internalType: "euint8", name: "yearsFounded", type: "uint256" },
      { internalType: "euint8", name: "employees", type: "uint256" },
      { internalType: "euint8", name: "tax", type: "uint256" },
      { internalType: "euint8", name: "revenue", type: "uint256" },
      { internalType: "euint8", name: "lawsuit", type: "uint256" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getOverallGrade",
    outputs: [{ internalType: "euint8", name: "grade", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getRatingTimestamp",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "hasRating",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "ratingCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "externalEuint8", name: "encCapital", type: "bytes32" },
      { internalType: "externalEuint8", name: "encYearsFounded", type: "bytes32" },
      { internalType: "externalEuint8", name: "encEmployees", type: "bytes32" },
      { internalType: "externalEuint8", name: "encTax", type: "bytes32" },
      { internalType: "externalEuint8", name: "encRevenue", type: "bytes32" },
      { internalType: "externalEuint8", name: "encLawsuit", type: "bytes32" },
      { internalType: "bytes", name: "inputProof", type: "bytes" },
    ],
    name: "submitAndCalculate",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "confidentialProtocolId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
